package release

import (
	"bufio"
	"fmt"
	"io"
	"strings"
)

// windowsAsset is the release-asset filename for the Windows amd64 binary.
const windowsAsset = "mdsmith-windows-amd64.exe"

// releaseBaseURL is the GitHub releases download prefix.
const releaseBaseURL = "https://github.com/jeduden/mdsmith/releases/download"

// ParseChecksumFor reads a sha256sum-format checksums.txt from r and
// returns the hex hash for the file named target. It returns an error
// if the target is not present.
func ParseChecksumFor(r io.Reader, target string) (string, error) {
	scanner := bufio.NewScanner(r)
	for scanner.Scan() {
		line := scanner.Text()
		// sha256sum format: "<hex>  <filename>" (two spaces) or
		// "<hex> *<filename>" (binary mode). We trim both variants.
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// Split on whitespace: first field is hash, rest is filename.
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		hash := fields[0]
		// The filename may be prefixed with '*' in binary mode.
		name := strings.TrimPrefix(fields[1], "*")
		if name == target {
			return hash, nil
		}
	}
	if err := scanner.Err(); err != nil {
		return "", fmt.Errorf("read checksums: %w", err)
	}
	return "", fmt.Errorf("%s: not found in checksums", target)
}

// RenderScoopManifest emits the JSON body for bucket/mdsmith.json in
// the jeduden/scoop-mdsmith bucket. version must be a bare semver
// (no leading "v"); hash is the SHA-256 of mdsmith-windows-amd64.exe
// from checksums.txt.
func RenderScoopManifest(version, hash string) string {
	url := fmt.Sprintf("%s/v%s/%s", releaseBaseURL, version, windowsAsset)
	autoupdateURL := strings.Replace(url, version, "$version", 1)
	var sb strings.Builder
	sb.WriteString("{\n")
	fmt.Fprintf(&sb, "  \"version\": %q,\n", version)
	sb.WriteString("  \"description\": \"Fast Markdown linter and formatter.\",\n")
	sb.WriteString("  \"homepage\": \"https://github.com/jeduden/mdsmith\",\n")
	sb.WriteString("  \"license\": \"MIT\",\n")
	fmt.Fprintf(&sb, "  \"url\": %q,\n", url)
	fmt.Fprintf(&sb, "  \"hash\": %q,\n", hash)
	sb.WriteString("  \"bin\": \"mdsmith.exe\",\n")
	sb.WriteString("  \"checkver\": {\n")
	sb.WriteString("    \"github\": \"https://github.com/jeduden/mdsmith\"\n")
	sb.WriteString("  },\n")
	sb.WriteString("  \"autoupdate\": {\n")
	fmt.Fprintf(&sb, "    \"url\": %q\n", autoupdateURL)
	sb.WriteString("  }\n")
	sb.WriteString("}\n")
	return sb.String()
}

// wingetPackageID is the WinGet package identifier.
const wingetPackageID = "jeduden.mdsmith"

// wingetPublisher is the publisher string in the locale manifest.
const wingetPublisher = "jeduden"

// RenderWingetManifests returns the three YAML files required by
// microsoft/winget-pkgs for a new version: the version manifest, the
// installer manifest, and the default locale manifest. The caller
// writes each string to the appropriate path under
// manifests/j/jeduden/mdsmith/<version>/ in the winget-pkgs fork.
// version must be a bare semver (no leading "v"); hash is the SHA-256
// of mdsmith-windows-amd64.exe from checksums.txt.
func RenderWingetManifests(version, hash string) []string {
	url := fmt.Sprintf("%s/v%s/%s", releaseBaseURL, version, windowsAsset)

	versionManifest := wingetVersionManifest(version)
	installerManifest := wingetInstallerManifest(version, url, hash)
	localeManifest := wingetLocaleManifest(version)

	return []string{versionManifest, installerManifest, localeManifest}
}

// wingetVersionManifest renders the version-level manifest.
func wingetVersionManifest(version string) string {
	var sb strings.Builder
	sb.WriteString("# Generated by `mdsmith-release render-winget-manifest`. Do not edit by hand.\n")
	sb.WriteString("# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json\n")
	sb.WriteString("\n")
	fmt.Fprintf(&sb, "PackageIdentifier: %s\n", wingetPackageID)
	fmt.Fprintf(&sb, "PackageVersion: %s\n", version)
	fmt.Fprintf(&sb, "DefaultLocale: en-US\n")
	fmt.Fprintf(&sb, "ManifestType: version\n")
	fmt.Fprintf(&sb, "ManifestVersion: 1.6.0\n")
	return sb.String()
}

// wingetInstallerManifest renders the installer manifest. The Windows
// asset is a bare CLI binary, not an installer, so it ships with
// InstallerType "portable": WinGet stores the binary and links it onto
// PATH itself rather than executing it as an installer. The exe/silent
// installer fields would make WinGet run `mdsmith-windows-amd64.exe /S`,
// which the linter rejects as a bad argument instead of installing.
// PortableCommandAlias names the PATH link `mdsmith`; without it WinGet
// would use the asset stem (mdsmith-windows-amd64).
func wingetInstallerManifest(version, url, hash string) string {
	var sb strings.Builder
	sb.WriteString("# Generated by `mdsmith-release render-winget-manifest`. Do not edit by hand.\n")
	sb.WriteString("# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json\n")
	sb.WriteString("\n")
	fmt.Fprintf(&sb, "PackageIdentifier: %s\n", wingetPackageID)
	fmt.Fprintf(&sb, "PackageVersion: %s\n", version)
	sb.WriteString("InstallerType: portable\n")
	sb.WriteString("Installers:\n")
	sb.WriteString("  - Architecture: x64\n")
	fmt.Fprintf(&sb, "    InstallerUrl: %s\n", url)
	fmt.Fprintf(&sb, "    InstallerSha256: %s\n", hash)
	sb.WriteString("    PortableCommandAlias: mdsmith\n")
	sb.WriteString("ManifestType: installer\n")
	sb.WriteString("ManifestVersion: 1.6.0\n")
	return sb.String()
}

// wingetLocaleManifest renders the default locale manifest.
func wingetLocaleManifest(version string) string {
	var sb strings.Builder
	sb.WriteString("# Generated by `mdsmith-release render-winget-manifest`. Do not edit by hand.\n")
	sb.WriteString("# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json\n")
	sb.WriteString("\n")
	fmt.Fprintf(&sb, "PackageIdentifier: %s\n", wingetPackageID)
	fmt.Fprintf(&sb, "PackageVersion: %s\n", version)
	sb.WriteString("PackageLocale: en-US\n")
	fmt.Fprintf(&sb, "Publisher: %s\n", wingetPublisher)
	sb.WriteString("PackageName: mdsmith\n")
	sb.WriteString("License: MIT\n")
	sb.WriteString("ShortDescription: Fast Markdown linter and formatter.\n")
	sb.WriteString("Description: |-\n")
	sb.WriteString("  mdsmith is a fast, cross-platform Markdown linter written in Go.\n")
	sb.WriteString("  It enforces formatting rules, keeps generated sections in sync,\n")
	sb.WriteString("  and ships a Language Server Protocol server for editor integration.\n")
	sb.WriteString("Tags:\n")
	sb.WriteString("  - markdown\n")
	sb.WriteString("  - linter\n")
	sb.WriteString("  - formatter\n")
	sb.WriteString("ManifestType: defaultLocale\n")
	sb.WriteString("ManifestVersion: 1.6.0\n")
	return sb.String()
}
